-- drop.sql

DROP TABLE reitingi   CASCADE CONSTRAINTS PURGE;
DROP TABLE spele      CASCADE CONSTRAINTS PURGE;

DROP TABLE kategorija CASCADE CONSTRAINTS PURGE;
DROP TABLE platforma  CASCADE CONSTRAINTS PURGE;
DROP TABLE zanrs      CASCADE CONSTRAINTS PURGE;
DROP TABLE studija    CASCADE CONSTRAINTS PURGE;
